Improve READMEs, fix typos
mrDIMAS/rg3d pull request #67
Opened 2020-12-29 21:38 UTC by martin-t

Let me know if you disagree with anything.

The logo might look better if it was a bit smaller but i haven't looked at how to edit the svg.

I changed the heading to "Rust Game 3D" because as i said on discord, it's not immediately obvious what RG3D stands for and i think this way it's more memorable.

There's also a way to center the heading/logo if you think it would look better.

What do you think about including the number of comments https://tokei.rs/b1/github/mrDIMAS/rg3d?category=comments among the badges?

I changed the bit about ECS/OOP because i think a lot of people imagine inheritance when they hear OOP and it might not evoke positive emotions, especially in the rust crowd ;)

2020-12-29 23:34 UTC, toyboot4e commented
Also, I wonder if we substitute WARNING to NOTE in sub crates' README.md so that they have positive nuance :)

2020-12-30 00:05 UTC, martin-t commented
Definitely, i didn't notice the subcrates has separate readmes. I skimmed them and made some more fixes.

2021-01-01 11:16 UTC, mrDIMAS requested changes
Could you please change that one comment? The rest looks good, it is a shame that I missed so many articles :smile:

2021-01-01 11:16 UTC, mrDIMAS commented on README.md
> +# Rust Game 3D
It should be **R**ust **G**ame engine **3D**, I think it is less confusing than Rust Game - which looks like it is game, not engine.

2021-01-01 11:26 UTC, mrDIMAS commented on README.md
> +# Rust Game 3D
Actually, I just realized that I can fix it by myself after merge

2021-01-01 11:27 UTC, merged